version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 18 # workaround https://github.com/aws/aws-codebuild-docker-images/issues/490
      - NODE_ENV=dev npm ci

  pre_build:
    on-failure: ABORT # or CONTINUE
    commands:
      - npm run test:format
      - npm run test:license
      - npm run test:lint
      - npm run test:types
      # - npm run test:audit
      - npm run test

  build:
    commands:
      # this is just to compile ts; serverless will run its own build at deploy
      - npm run build

artifacts:
  files:
    - "**/*"
  enable-symlinks: yes
